
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:timsc/opencv-3.4 -y && apt-get update -q; fi

addons:
  apt:
    packages:
      - libboost-all-dev
      - libopencv-dev
  homebrew:
    packages:
      - boost
      - cmake
      - opencv

script:
  - mkdir -p build/
  - cd build/
  - cmake .. && make -j

language: cpp