language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ./scripts/InstallOpenCV.sh; fi

addons:
  apt:
    packages:
      - libboost-all-dev
  homebrew:
    packages:
      - boost
      - cmake
      - opencv

script:
  - mkdir -p build/
  - cd build/
  - cmake .. && make -j