language: cpp
matrix:
  include:
    - osx: linux
      dist: xenial
      compiler:
        - clang
        - gcc
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:timsc/opencv-3.4 -y && sudo apt-get update -q && sudo apt-get install libopencv-dev -y; fi

addons:
  apt:
    packages:
      - libboost-all-dev
  homebrew:
    packages:
      - boost
      - cmake
      - opencv

script:
  - mkdir -p build/
  - cd build/
  - cmake .. && make -j